# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 15:31
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20161209_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerclass',
            name='address',
            field=models.CharField(default=datetime.datetime(2016, 12, 9, 15, 31, 2, 892785, tzinfo=utc), max_length=50, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerclass',
            name='bloodgroup',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], default=datetime.datetime(2016, 12, 9, 15, 31, 8, 527312, tzinfo=utc), max_length=4, verbose_name='Blood group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerclass',
            name='city',
            field=models.CharField(choices=[('narayanghat', 'narayanghat'), ('pokhara', 'pokhara'), ('kathmandu', 'kathmandu'), ('biratnagar', 'biratnagar')], default=datetime.datetime(2016, 12, 9, 15, 31, 20, 493860, tzinfo=utc), max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerclass',
            name='contact_number',
            field=models.CharField(default=datetime.datetime(2016, 12, 9, 15, 31, 28, 246726, tzinfo=utc), max_length=10, verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerclass',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 12, 9, 15, 31, 35, 719233, tzinfo=utc), max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerclass',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default=datetime.datetime(2016, 12, 9, 15, 31, 52, 237152, tzinfo=utc), max_length=6, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerclass',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='registerclass',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='%s%s', unique_with=['first_name', 'last_name']),
        ),
    ]
